name: Build 1 Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk unzip git wget zip \
            build-essential autoconf automake libtool pkg-config \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev libreadline-dev \
            libgdbm-dev libbz2-dev liblzma-dev libxml2-dev libxslt1-dev \
            libjpeg-dev libfreetype6-dev libpng-dev \
            libavcodec-dev libavformat-dev libswscale-dev \
            libtiff5-dev libblas-dev liblapack-dev gfortran ccache

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cython==0.29.36 kivy==2.1.0 buildozer==1.3.0

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghost-apk
          path: bin/*.apk
